'use strict';
const fs=require('node:fs'),assert=require('node:assert/strict');
const {context,mulberry32}=require('./simulation-context.cjs');
const {runner}=require('./economy-simulation.cjs');
const source=fs.readFileSync(require('node:path').join(__dirname,'..','game.js'),'utf8');
const checks=[];
async function test(name,work){await work();checks.push(name)}
const json=(c,code)=>JSON.parse(c.run('JSON.stringify('+code+')'));
function fresh(map='classic'){
 const c=context(source,11),events=[];c.capture=cfg=>events.push(cfg);
 c.run(`initializeGame('${map}');showContinueModal=async cfg=>capture(cfg);`);
 return{c,events};
}
async function start(map,first,mode='rounds'){
 const h=fresh(map),{c,events}=h,order=[];
 c.run(`selectedMapId='${map}';MAP_PRESETS['${map}'].economy.secondPlayerBonus=500;`);
 c.checkPrompt=cfg=>{order.push(cfg.label);if(cfg.label==='先手决定'){assert.deepEqual(json(c,'state.players.map(p=>p.cash)'),[c.run('getMapEconomy().startCash'),c.run('getMapEconomy().startCash')]);assert.equal(c.run('state.initiativeResolved'),false);return'flip'}return mode};
 c.capture=cfg=>{events.push(cfg);if(cfg.label==='先手决定'){assert.equal(c.run('state.firstPlayerIndex'),first);const expected=[c.run('getMapEconomy().startCash'),c.run('getMapEconomy().startCash')];expected[1-first]+=500;assert.deepEqual(json(c,'state.players.map(p=>p.cash)'),expected)}};
 c.Math.random=()=>first===0?.25:.75;
 c.run('showModal=async cfg=>checkPrompt(cfg);');await c.run('startNewGame()');
 return {...h,order};
}
function chanceCase(kind,map='classic'){
 const h=fresh(map),{c}=h;
 c.run(`state.players[0].isAi=true;state.players[0].position=state.board.find(t=>t.special?.type==='chance').index;state.players[1].position=2;state.board[1].lot.ownerId='human';state.board[1].lot.level=1;state.board[2].lot.ownerId='ai';state.board[2].lot.level=1;`);
 const firstRoll={renovation:.1,district:.3,shield:.44,express:.55,swap:.7,bank:.8,bonus:.95}[kind];
 const values=[firstRoll,.01];c.Math.random=()=>values.shift()??.01;
 h.run=()=>c.run('resolveChance(state.players[0],state.board[state.players[0].position],state.sessionId)');
 return h;
}
(async()=>{
 for(const map of ['classic','compact','expansion'])for(const first of [0,1])await test(`${map} seat${first}: real startNewGame pays only the second player before first-result display`,async()=>{const {c,events}=await start(map,first);assert.equal(c.run('state.currentPlayerIndex'),first);assert.equal(c.run('state.openingCompensation.playerId'),first===0?'ai':'human');assert(events.some(e=>/开局补给已到账/.test(e.message)));const cash=json(c,'state.players.map(p=>p.cash)');assert.equal(c.run(`settleFirstPlayer(${first===0})`),false);assert.deepEqual(json(c,'state.players.map(p=>p.cash)'),cash);const counts=[0,0];while(!c.run('state.gameOver')){counts[c.run('state.currentPlayerIndex')]++;c.run('endTurn()')}assert.deepEqual(counts,[c.run('getMaxRounds()'),c.run('getMaxRounds()')]);});
 await test('bankruptcy start gets transparent supply without promising a round cap',async()=>{const {events}=await start('expansion',1,'bankruptcy');const e=events.find(e=>e.label==='先手决定');assert.match(e.message,/破产淘汰制/);assert.doesNotMatch(e.message,/40 个正常轮次/)});
 await test('shipping 500/500/300 startup and 300/300/450 lap income through actual entry points',async()=>{for(const [map,initial,supply,lap]of [['classic',1600,500,300],['compact',1600,500,300],['expansion',2000,300,450]])for(const first of [0,1]){const {c,events}=fresh(map);c.run(`selectedMapId='${map}';showModal=async cfg=>cfg.label==='先手决定'?'flip':'rounds'`);c.Math.random=()=>first===0?.25:.75;await c.run('startNewGame()');const cash=[initial,initial];cash[1-first]+=supply;assert.deepEqual(json(c,'state.players.map(p=>p.cash)'),cash);assert.equal(c.run('state.openingCompensation.amount'),supply);c.run('state.players[0].position=state.board.length-1');await c.run('animateMovement(state.players[0],1,state.sessionId)');assert.equal(c.run('state.players[0].cash'),cash[0]+lap);assert.equal(events.find(e=>e.label==='市政府补给').drama.amount,lap)}});
 await test('restart while coin prompt awaits cannot pay or select starter in new session',async()=>{const {c}=fresh();let release,ready;const reached=new Promise(resolve=>ready=resolve);c.prompt=cfg=>{if(cfg.label==='先手决定'){ready();return new Promise(resolve=>release=resolve)}return Promise.resolve('rounds')};c.run('showModal=cfg=>prompt(cfg)');const pending=c.run('startNewGame()');await reached;c.run('initializeGame("compact")');const before=json(c,'state.players.map(p=>p.cash)');release('flip');await pending;assert.equal(c.run('state.initiativeResolved'),false);assert.deepEqual(json(c,'state.players.map(p=>p.cash)'),before);assert.equal(c.run('state.openingCompensation'),null)});
 await test('restart during paid coin reveal clears old compensation and ignores old continuation',async()=>{const {c}=fresh();let release,ready;const reached=new Promise(resolve=>ready=resolve);c.run('MAP_PRESETS.classic.economy.secondPlayerBonus=500;showModal=async cfg=>cfg.label==="先手决定"?"flip":"rounds"');c.hold=()=>{ready();return new Promise(resolve=>release=resolve)};c.run('showContinueModal=cfg=>hold()');const pending=c.run('startNewGame()');await reached;assert.equal(c.run('state.initiativeResolved'),true);c.run('initializeGame("classic")');release();await pending;assert.equal(c.run('state.openingCompensation'),null);assert.deepEqual(json(c,'state.players.map(p=>p.cash)'),[1600,1600])});
 await test('dice extras stay inside one normal turn; relief rest consumes one normal turn',async()=>{const {c}=fresh();c.run('animateDiceRoll=async()=>6;animateMovement=async()=>{};resolveLanding=async()=>{}');await c.run('processTurn(currentPlayer())');assert.equal(c.run('state.currentPlayerIndex'),1);assert.equal(c.run('state.round'),1);await c.run('processTurn(currentPlayer())');assert.equal(c.run('state.round'),2);c.run('currentPlayer().effects.bankruptcyRelief=true');await c.run('processTurn(currentPlayer())');assert.equal(c.run('state.currentPlayerIndex'),1);assert.equal(c.run('state.round'),2)});
 for(const kind of ['renovation','district','shield','express','swap','bank','bonus'])await test(`chance ${kind}: actual state and explicit truthful event payload`,async()=>{
  const {c,events,run}=chanceCase(kind);const before=json(c,'state.players.map(p=>({cash:p.cash,position:p.position}))');
  let landed=0;c.markLanding=()=>landed++;if(kind==='express'||kind==='swap')c.run('resolveLanding=async()=>markLanding()');await run();
  const event=events.find(e=>e.drama?.chanceKind===kind);assert(event);const d=event.drama;assert.equal(d.actor.id,'human');assert.equal(d.rival.id,'ai');assert(d.outcomeLabel);assert(d.tiles.length);assert.deepEqual(Array.from(d.triggerTiles),[before[0].position]);
  if(kind==='renovation'){assert.equal(c.run('state.board[1].lot.level'),2);assert.equal(d.type,'build');assert.equal(d.amount,0)}
  if(kind==='district'){assert.equal(c.run('state.board[1].lot.level'),2);assert.equal(c.run('state.board[2].lot.level'),2);assert.equal(c.run('state.board[3].lot.level'),1);assert.equal(c.run('state.board[1].lot.ownerId'),'human');assert.equal(c.run('state.board[2].lot.ownerId'),'ai');assert.equal(d.amount,0)}
  if(kind==='shield'){assert.equal(c.run('state.players[0].effects.shield'),true);assert.equal(d.type,'card');assert.equal(d.amount,0)}
  if(kind==='express'){assert.equal(landed,1);assert.equal(c.run('state.players[0].position'),1);assert.deepEqual(json(c,'state.players.map(p=>p.cash)'),before.map(p=>p.cash));assert.equal(c.run('state.passedStartThisTurn'),false)}
  if(kind==='swap'){assert.equal(landed,0);assert.deepEqual(json(c,'state.players.map(p=>p.position)'),before.map(p=>p.position).reverse())}
  if(kind==='bank'){assert.equal(c.run('state.bankPool'),d.amount);assert.equal(d.to.id,'bank');assert.equal(d.from.id,'city');assert.deepEqual(Array.from(d.tiles),[4]);assert.deepEqual(json(c,'state.players.map(p=>p.cash)'),before.map(p=>p.cash));await c.run('resolveSpecialTile(state.players[1],state.board.find(t=>t.special?.type==="bank"),state.sessionId)');assert.equal(c.run('state.bankPool'),0);assert.equal(c.run('state.players[1].cash'),before[1].cash+d.amount)}
  if(kind==='bonus'){assert.equal(d.beneficiaries.length,2);assert.deepEqual(json(c,'state.players.map(p=>p.cash)'),before.map(p=>p.cash+d.amount));assert.equal(d.type,'income')}
 });
 await test('renovation without owned land improves an unowned lot, does not grant ownership',async()=>{const {c,events,run}=chanceCase('renovation');c.run('state.board[1].lot.ownerId=null');await run();assert.equal(c.run('state.board[1].lot.ownerId'),null);assert.equal(c.run('state.board[1].lot.level'),2);assert.match(events[0].message,/无主地产/)});
 await test('district upgrades a large lot exactly once across its two aliases',async()=>{const {c,events,run}=chanceCase('district');const values=[.3,.3];c.Math.random=()=>values.shift()??.1;await run();assert.equal(c.run('state.board[5].lot.level'),1);assert.equal(c.run('state.board[6].lot.level'),1);assert.equal(c.run('state.board[7].lot.level'),1);assert.equal(c.run('state.board[8].lot.level'),1);assert.equal(events[0].drama.tiles.length,2)});
 await test('express into rival property charges one actual toll and preserves reverse effect',async()=>{const {c,events,run}=chanceCase('express');c.run('state.players[0].effects.reversed=true');const targetOffset=c.run('state.board.filter(t=>t.lot).findIndex(t=>t.index===2)'),length=c.run('state.board.filter(t=>t.lot).length');const values=[.55,(targetOffset+.5)/length];c.Math.random=()=>values.shift()??.1;const before=json(c,'state.players.map(p=>p.cash)');await run();const fee=c.run('state.board[2].lot.tolls[1]');assert.deepEqual(json(c,'state.players.map(p=>p.cash)'),[before[0]-fee,before[1]+fee]);assert.equal(c.run('state.players[0].effects.reversed'),true);assert.equal(c.run('state.players[0].position'),2)});
 await test('restart during express reveal prevents destination settlement in new game',async()=>{const {c,run}=chanceCase('express');let release;c.hold=()=>new Promise(resolve=>release=resolve);c.run('showContinueModal=()=>hold();resolveLanding=async()=>{throw Error("Stale landing")}');const pending=run();await Promise.resolve();c.run('initializeGame("compact")');release();await pending;assert.equal(c.run('state.currentMapId'),'compact');assert.deepEqual(json(c,'state.players.map(p=>p.cash)'),[1600,1600])});
 await test('full city + held shield + same position cannot draw empty/inapplicable event',async()=>{for(const roll of [0,.3,.6,.999]){const {c,events,run}=chanceCase('renovation');c.run('state.board.forEach(t=>{if(t.lot)t.lot.level=3});state.players[0].effects.shield=true;state.players[1].position=state.players[0].position;resolveLanding=async()=>{}');c.Math.random=()=>roll;await run();assert(['express','bank','bonus'].includes(events[0].drama.chanceKind));assert(c.run('state.board.filter(t=>t.lot).every(t=>t.lot.level===3)'))}});
 await test('map economy returns independent values and preserves classic defaults',async()=>{const {c}=fresh();assert.equal(c.run('getMapEconomy("classic").startCash'),1600);assert.equal(c.run('getMapEconomy("classic").startBonus'),300);assert.equal(c.run('getMapEconomy("compact").startCash'),1600);assert.equal(c.run('getMapEconomy("expansion").startBonus'),450);c.run('getMapEconomy().startCash=99');assert.equal(c.run('getMapEconomy().startCash'),1600)});
 await test('real-start fast runner repeats exactly and mirrors both starter roles with compensation',async()=>{for(const map of ['classic','compact','expansion']){const run=runner(source,map,{secondPlayerBonus:500});for(const seed of [93101,93102]){const a=await run(seed,0),b=await run(seed,1),again=await run(seed,0);assert.deepEqual(a,again);assert.deepEqual(a.cash,[...b.cash].reverse());assert.equal(a.score,b.score);assert.equal(a.randomCalls,b.randomCalls);assert.deepEqual(a.base,b.base)}}});
 await test('instrumented reused VM matches fresh uninstrumented real-start games and RNG counts',async()=>{for(const map of ['classic','compact','expansion'])for(const first of [0,1]){const seed=94201,c=context(source,seed),random=mulberry32(seed);let forceCoin=false,randomCalls=0;c.coin=()=>{forceCoin=true};c.Math.random=()=>{const value=random();randomCalls++;if(forceCoin){forceCoin=false;return first===0?.25:.75}return value};c.run(`PLAYER_DEFS.forEach(p=>p.isAi=true);selectedMapId='${map}';showModal=async cfg=>{if(cfg.label==='先手决定'){coin();return 'flip'}return 'rounds'}`);await c.run('startNewGame()');const turns=[0,0];while(!c.run('state.gameOver')){turns[c.run('state.currentPlayerIndex')]++;await c.run('processTurn(currentPlayer())')}const fast=await runner(source,map)(seed,first);assert.deepEqual(fast.cash,json(c,'state.players.map(p=>p.cash)'));assert.deepEqual(fast.base,turns);assert.equal(fast.randomCalls,randomCalls)}});
 console.log('PASS',checks.length,'targeted real-start, turn, chance, cash and session checks');
})().catch(error=>{console.error(error);process.exitCode=1});
